### ISSUE TITLE
Segmentation fault for large configurations

### ISSUE THREAD

**Issue by dsidoren** [ecmwf/multio#11]
https://github.com/ecmwf/multio/blob/265458f9e57c5d081049e43c1339be6b561527aa/src/multio/tools/multio-replay-nemo-fapi.f90#L327

Our implementation of MULTIO in FESOM has been successful for small, unstructured meshes with a smaller number of CPUs, typically less than 300,000 gridpoints. However, when using larger configurations, the system often crashes at the "mio%write_domain" call with a non-traceable segmentation fault. We attempted to address this issue by experimenting with different MPI implementations (OpenMPI and IntelMPI), compilers (Intel and GNU Fortran), stack sizes, SLURM environment settings etc. on the Levante DKRZ system, but with no success. For small unstructured meshes with medium resolutions and fewer than 200,000 gridpoints can run smoothly using 144 CPUs for the model and 6 CPUs for the MIO server. However, larger setups with 5 million surface grid points using 2048 CPUs for FESOM and 6 (we experimented with different numbers) for the MIO server are not able to run and crash at the "mio%write_domain" call. Despite using the latest version of MULTIO, the issue remains unchanged. The exact line of the crash can be found in our GitHub repository at the following link: https://github.com/FESOM/fesom2/blob/f8dbc6bb777039dfc88f845b6b10f0df05ad1e24/src/gen_modules_partitioning.F90#L695
and the yaml configuration file is located at https://github.com/FESOM/fesom2/blob/MULTIO/work/multio-server.yaml.

**Comment by geier1993** [comment]
Hey,
sorry for the late response. Right now it's hard to reproduce the problem. 
However, let's discuss you multi-server.yaml.

```
    - name : fesom-stream
      actions :
        - type : select
          match :
          - category : [fesom-node-output]
        - type : transport
          target : server
          hash-keys: [category, name]
        - type : single-field-sink
        - type : aggregation
```

The actions after the transport should have no effect and should not be called at all - you should be able to remove the single-field-sink and the aggregation. 



```
    - name : fesom-output
      actions :
        - type : select
          match :
           - category : [fesom-domain-nodemap, fesom-domain-elemmap]
        - type : transport
          target : server
```

Here you filter on category "fesom-domain-nodemap" and "fesom-domain-elemmap" and then send it to the server.
In your server these categories do not get filtered expclicitly. However "write_domain" and "write_mask" calls with these categories will arrive there....
In your code I can see that your setting the category "fesom-domain-nodemap" for both write_domain calls. So that should be fine as well (although I think you intended to use category "besom-domain-elemmap" for the second call).

Now I can see that you are not writing fields yet?
So the "write_domain" call causing problems is the very first message sending data at all...
That means on our side the segmentation fault might result from the message listening & handling or from the domain handling logic....
However, I could not identify critical paths that cause might cause problems for 2048 messages but not for 144 messages.

Internally we use some queues with a configurable size - they are not documented yet (sorry for that, but we may also have redesigns and proper benchmarks).

* env: MULTIO_MESSAGE_QUEUE_SIZE: The queue for each MPI server (in your case 6) where messages can be put in. Default size is 1024*1024. 
* env: MULTIO_MPI_POOL_SIZE: 128 - Count of buffers preallocated for accepting messages
* env: MULTIO_MPI_BUFFER_SIZE: 64*1024*1024 - Buffer size...

You may want to increase some of these and test if it is working. Limiting the message queue and pool size should usually just result in a blocking behaviour but continue working....
However the buffer sized is just loosely checked with an ASSERT... maybe try increasing that one first...


I hope that helps you. Otherwise @dsarmany might have other ideas next week.

**Comment by geier1993** [comment]
do you know how large your buffer is?

**Comment by dsidoren** [comment]
Hi, we included the suggested changes. We run the model on a standard dkrz levante partition: https://docs.dkrz.de/doc/levante/configuration.html (the first entry here). We played with the environment settings etc. and with no success. During the last attempt our unstructured grid contained 5,576,658 grid points. We used 2048 cores for the model and 2 (instead of available 128, placed at the same node with 256GB of memory) for the server. Still the segmentation fault. 

Note: accidentally the model could reach the writing statement and got stuck here: https://github.com/FESOM/fesom2/blob/3f1bdcaa24958020fb5d8c2ac8d922d758b7c742/src/io_meandata.F90#L1767

We included write_step_complete to flush the buffered data but it causes MULTIO to crash. It is seemingly related to the appearance of "levels" in the metadata.

**Comment by dsarmany** [comment]
Hi,

Did you managed to run a configuration where the only thing you do is to communicate the domain information? A minimal configuration like this:
```yaml
    - name : fesom-output
      actions :
        - type : select
          match :
           - category : [fesom-domain-nodemap]
        - type : transport
          target : server
```

Also, make sure you don't call `mio%write_field`, nor `mio%write_step_complete`.

This would be a sanity check to see whether getting the domain mappings stored on every server is causing the crash. The domain information is notable because it is an all-to-all communication: every model task sends its own bit to every server task. It is not a problem for structured mapping because the information is compact. For an explicit list of indices, the data is much larger, although I would still not expect it be a problem in general.

You can also try increasing the number of servers gradually and play with the number of servers you put on a single node. Could the crash be an OOM problem, or does it look like a different memory corruption?
