### ISSUE TITLE
no level metadata for models other than NEMO

### ISSUE THREAD

**Issue by dsidoren** [ecmwf/multio#17]
Thanks for your previous efforts to make MULTIO generic especially for parts which had metadata specific for NEMO. We found few other related issues that made using mapping and getting levels in grib from FESOM hard. 

https://github.com/ecmwf/multio/blob/c767b3c75d19bfa6e920806cee4cf282477d1cec/src/multio/action/encode/GribEncoder.cc#L320-L331

In case not NEMO and category name not starting with "ocean"  isOcean will return FALSE. Even if category name starts with "ocean" nemo is hard coded at few places of these functions (eg. msg.metadata().getString("nemoParam")).
This implies that if you are not NEMO the metadata (such as a number of layer) will not be set. For the purpose of running MIO with FESOM we had to modify this code here as following:

´´´
void GribEncoder::setFieldMetadata(const message::Message& msg) {
    if (isOcean(msg.metadata())) {
        setOceanMetadata(msg);
    }
    else {
        const auto& metadata = msg.metadata();
        auto queriedMarsFields = setMarsKeys(*this, metadata);
        applyOverwrites(*this, metadata);
        setEncodingSpecificFields(*this, metadata);
        setDateAndStatisticalFields(*this, metadata, queriedMarsFields);
        if (metadata.getString("typeOfLevel") == "oceanModelLayer") {
           auto level = metadata.getLong("level");
           ASSERT(level > 0);
           setValue("scaledValueOfFirstFixedSurface", level - 1);
           setValue("scaledValueOfSecondFixedSurface", level);
        }
    }
}
´´´
This also assumes that the metadata.getString("typeOfLevel") exists. We think this code should be more generic,

**Comment by dsarmany** [comment]
Hi @dsidoren -- Yes, the fact that we treat ocean encoding as a special case is very ugly, and we are working on new ways/designs to improve that in future versions.

For now, however, we need have a way to distinguish ocean data from atmosphere/wave data, because there are some special encoding rules we have to follow for these. The convention in `multio` is to expect the 'category' key to start with 'ocean', thus indicating that the field is coming from an ocean model. That is less restrictive as it seems because it is a member of the field's metadata, which the model has to set anyway. It is not NEMO-specific -- there is no reason why other ocean models such as FESOM could not follow the same convention.

Equally, 'nemoParam' is a bad name; it should probably be called 'oceanParam'. It is also probably not needed in the encoder at all and reference to it could be removed. The important point is that for the encoder to work properly, we have to provide a metadata mapping between some ocean metadata and grib metadata. This is done in `nemo-to-grib.yaml`. This is NEMO-specific and it should be. I would expect for FESOM to see something similar, such `fesom-to-grib.yaml`.

The fundamental question is whether there is an existing and complete GRIB data model for FESOM. Much of the complexity in encoding ocean fields comes from setting the keys associated with the grids, such as `unstructuredGridType`, `unstructuredGridSubtype`, `uuidOfHGrid`, etc. I'm not aware of these being defined/supported for FESOM and thus what the output GRIB data should actually look like.

**Comment by suvarchal** [comment]
@dsarmany Thanks for the tip, with @dsidoren  we did make some progress in being an "ocean", here is one hurdle, probably the last one. 
 https://github.com/ecmwf/multio/blob/c767b3c75d19bfa6e920806cee4cf282477d1cec/src/multio/action/encode/Encode.cc#L101-L105 

When the block setting coordinates is commented out we can be an an ocean. As mentioned we don't want to be making such changes to multio unless necessary, what would you recommend to do in this case: how to we deal with this block for FESOM via multio, eccodes ?
